baseurl = "https://intel4coro.github.io/ViB-public/"
DefaultContentLanguage = "en"
title = "Virtual Research Building (ViB)"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
paginate = 20
pygmentsCodefencesGuessSyntax = true

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[Params]
 homeTitle = "Our virtual research and training building for cognition-enabled robotics" # Set a different text for the header on the home page
  subtitle = ""
  mainSections = ["posts"]
  logo = "img/logo.png" # Expecting square dimensions
  favicon = "favicon.ico"
  dateFormat = "2 January 2006"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."
  rightSideImg = "img/ViB_neutral.jpg"
  showHomeBigImg = true


[[Params.bigimg]]
 src = "img/Neujahrskarte_2023_ViB_layer_3.jpg"

[[Params.bigimg]]
 src = "img/Neujahrskarte_2023_ViB_layer_5.jpg"
 
[[Params.bigimg]]
 src = "img/Neujahrskarte_2023_ViB_layer_6.jpg"

[[Params.bigimg]]
 src = "img/Neujahrskarte_2023_ViB_layer_9.jpg"

[[Params.bigimg]]
 src = "img/Neujahrskarte_2023_ViB_layer_10.jpg"

[[Params.bigimg]]
 src = "img/Neujahrskarte_2023_ViB_layer_11.jpg"


[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  website = "https://ai.uni-bremen.de/"
  email = "ai-office@cs.uni-bremen.de "
  github = "IntEL4CoRo"
  youtube = "agkiunibremen"

[[menu.main]]
    name = "Contact"
    url = "page/contact/"
    weight = 1
